<?php

return [
    // Essential currency mappings (most commonly used)
    'mappings' => [
        'NGN' => ['main' => 'Naira', 'sub' => 'Kobo'],
        'USD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'EUR' => ['main' => 'Euros', 'sub' => 'Cents'],
        'GBP' => ['main' => 'Pounds', 'sub' => 'Pence'],
        'JPY' => ['main' => 'Yen', 'sub' => 'Sen'],
        'CNY' => ['main' => 'Yuan', 'sub' => 'Fen'],
        'INR' => ['main' => 'Rupees', 'sub' => 'Paisa'],
        'CAD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'AUD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'CHF' => ['main' => 'Francs', 'sub' => 'Rappen'],
        'MYR' => ['main' => 'Ringgit', 'sub' => 'Sen'],
        'SGD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'THB' => ['main' => 'Baht', 'sub' => 'Satang'],
        'IDR' => ['main' => 'Rupiah', 'sub' => 'Sen'],
        'PHP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'KRW' => ['main' => 'Won', 'sub' => 'Jeon'],
        'VND' => ['main' => 'Dong', 'sub' => 'Xu'],
        'ZAR' => ['main' => 'Rand', 'sub' => 'Cents'],
        'KES' => ['main' => 'Shillings', 'sub' => 'Cents'],
        'GHS' => ['main' => 'Cedis', 'sub' => 'Pesewas'],
        'EGP' => ['main' => 'Pounds', 'sub' => 'Piastres'],
        'AED' => ['main' => 'Dirhams', 'sub' => 'Fils'],
        'SAR' => ['main' => 'Riyals', 'sub' => 'Halala'],
        'KWD' => ['main' => 'Dinars', 'sub' => 'Fils'],
        'BHD' => ['main' => 'Dinars', 'sub' => 'Fils'],
        'OMR' => ['main' => 'Rials', 'sub' => 'Baisa'],
        'QAR' => ['main' => 'Riyals', 'sub' => 'Dirhams'],
        'JOD' => ['main' => 'Dinars', 'sub' => 'Piastres'],
        'TND' => ['main' => 'Dinars', 'sub' => 'Millimes'],
        'TRY' => ['main' => 'Lira', 'sub' => 'Kuruş'],
        'RUB' => ['main' => 'Rubles', 'sub' => 'Kopecks'],
        'UAH' => ['main' => 'Hryvnia', 'sub' => 'Kopiyky'],
        'NPR' => ['main' => 'Rupees', 'sub' => 'Paisa'],
        'PKR' => ['main' => 'Rupees', 'sub' => 'Paisa'],
        'LKR' => ['main' => 'Rupees', 'sub' => 'Cents'],
        'BDT' => ['main' => 'Taka', 'sub' => 'Poisha'],
        'BRL' => ['main' => 'Reais', 'sub' => 'Centavos'],
        'MXN' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'ARS' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'CLP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'COP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'PEN' => ['main' => 'Soles', 'sub' => 'Céntimos'],
        'NZD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'HKD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'TWD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'SEK' => ['main' => 'Krona', 'sub' => 'Öre'],
        'NOK' => ['main' => 'Krone', 'sub' => 'Øre'],
        'DKK' => ['main' => 'Krone', 'sub' => 'Øre'],
        'ISK' => ['main' => 'Krona', 'sub' => 'Aurar'],
        'PLN' => ['main' => 'Zloty', 'sub' => 'Grosz'],
        'CZK' => ['main' => 'Koruna', 'sub' => 'Haléř'],
        'HUF' => ['main' => 'Forint', 'sub' => 'Fillér'],
        'RON' => ['main' => 'Lei', 'sub' => 'Bani'],
        'ILS' => ['main' => 'Shekels', 'sub' => 'Agorot'],
        'BTC' => ['main' => 'Bitcoin', 'sub' => 'Satoshi'],

        // Additional currencies from PaymentCurrencyHelper
        'AFA' => ['main' => 'Afghanis', 'sub' => 'Puls'],
        'ALL' => ['main' => 'Lek', 'sub' => 'Qindarka'],
        'DZD' => ['main' => 'Dinars', 'sub' => 'Centimes'],
        'AOA' => ['main' => 'Kwanza', 'sub' => 'Cêntimos'],
        'AMD' => ['main' => 'Drams', 'sub' => 'Luma'],
        'AZN' => ['main' => 'Manat', 'sub' => 'Qəpik'],
        'BBD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'BGN' => ['main' => 'Leva', 'sub' => 'Stotinki'],
        'BIF' => ['main' => 'Francs', 'sub' => 'Centimes'],
        'BMD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'BND' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'BOB' => ['main' => 'Bolivianos', 'sub' => 'Centavos'],
        'BAM' => ['main' => 'Marks', 'sub' => 'Fening'],
        'BWP' => ['main' => 'Pula', 'sub' => 'Thebe'],
        'BYN' => ['main' => 'Ruble', 'sub' => 'Kopecks'],
        'BZD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'XOF' => ['main' => 'Francs', 'sub' => 'Centimes'],
        'XAF' => ['main' => 'Francs', 'sub' => 'Centimes'],
        'XPF' => ['main' => 'Francs', 'sub' => 'Centimes'],
        'CLP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'COP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'CRC' => ['main' => 'Colones', 'sub' => 'Céntimos'],
        'HRK' => ['main' => 'Kuna', 'sub' => 'Lipa'],
        'CUP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'DKK' => ['main' => 'Krone', 'sub' => 'Øre'],
        'DOP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'XCD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'EGP' => ['main' => 'Pounds', 'sub' => 'Piastres'],
        'ERN' => ['main' => 'Nakfa', 'sub' => 'Cents'],
        'ETB' => ['main' => 'Birr', 'sub' => 'Santim'],
        'FJD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'GMD' => ['main' => 'Dalasis', 'sub' => 'Bututs'],
        'GEL' => ['main' => 'Lari', 'sub' => 'Tetri'],
        'GTQ' => ['main' => 'Quetzales', 'sub' => 'Centavos'],
        'GGP' => ['main' => 'Pounds', 'sub' => 'Pence'],
        'GYD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'HTG' => ['main' => 'Gourdes', 'sub' => 'Centimes'],
        'HNL' => ['main' => 'Lempiras', 'sub' => 'Centavos'],
        'HKD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'HUF' => ['main' => 'Forint', 'sub' => 'Fillér'],
        'ISK' => ['main' => 'Krona', 'sub' => 'Aurar'],
        'INR' => ['main' => 'Rupees', 'sub' => 'Paisa'],
        'IDR' => ['main' => 'Rupiah', 'sub' => 'Sen'],
        'IRR' => ['main' => 'Rials', 'sub' => 'Dinars'],
        'IMP' => ['main' => 'Pounds', 'sub' => 'Pence'],
        'ILS' => ['main' => 'Shekels', 'sub' => 'Agorot'],
        'JMD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'JOD' => ['main' => 'Dinars', 'sub' => 'Piastres'],
        'KZT' => ['main' => 'Tenge', 'sub' => 'Tiin'],
        'KES' => ['main' => 'Shillings', 'sub' => 'Cents'],
        'KGS' => ['main' => 'Soms', 'sub' => 'Tyiyn'],
        'KHR' => ['main' => 'Riels', 'sub' => 'Sen'],
        'KMF' => ['main' => 'Francs', 'sub' => 'Centimes'],
        'KPW' => ['main' => 'Won', 'sub' => 'Chon'],
        'KRW' => ['main' => 'Won', 'sub' => 'Jeon'],
        'KWD' => ['main' => 'Dinars', 'sub' => 'Fils'],
        'KYD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'LAK' => ['main' => 'Kip', 'sub' => 'Att'],
        'LBP' => ['main' => 'Pounds', 'sub' => 'Piastres'],
        'LSL' => ['main' => 'Loti', 'sub' => 'Sente'],
        'LRD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'LYD' => ['main' => 'Dinars', 'sub' => 'Dirhams'],
        'MOP' => ['main' => 'Patacas', 'sub' => 'Avo'],
        'MKD' => ['main' => 'Denars', 'sub' => 'Deni'],
        'MGA' => ['main' => 'Ariary', 'sub' => 'Iraimbilanja'],
        'MWK' => ['main' => 'Kwacha', 'sub' => 'Tambala'],
        'MYR' => ['main' => 'Ringgit', 'sub' => 'Sen'],
        'MVR' => ['main' => 'Rufiyaa', 'sub' => 'Laari'],
        'MRO' => ['main' => 'Ouguiya', 'sub' => 'Khoums'],
        'MUR' => ['main' => 'Rupees', 'sub' => 'Cents'],
        'MXN' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'MDL' => ['main' => 'Lei', 'sub' => 'Bani'],
        'MAD' => ['main' => 'Dirhams', 'sub' => 'Centimes'],
        'MNT' => ['main' => 'Tugrik', 'sub' => 'Möngö'],
        'MZN' => ['main' => 'Meticais', 'sub' => 'Centavos'],
        'MMK' => ['main' => 'Kyats', 'sub' => 'Pya'],
        'NAD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'NPR' => ['main' => 'Rupees', 'sub' => 'Paisa'],
        'NIO' => ['main' => 'Córdobas', 'sub' => 'Centavos'],
        'NGN' => ['main' => 'Naira', 'sub' => 'Kobo'],
        'NOK' => ['main' => 'Krone', 'sub' => 'Øre'],
        'OMR' => ['main' => 'Rials', 'sub' => 'Baisa'],
        'PKR' => ['main' => 'Rupees', 'sub' => 'Paisa'],
        'PAB' => ['main' => 'Balboas', 'sub' => 'Céntimos'],
        'PYG' => ['main' => 'Guaraníes', 'sub' => 'Céntimos'],
        'PEN' => ['main' => 'Soles', 'sub' => 'Céntimos'],
        'PHP' => ['main' => 'Pesos', 'sub' => 'Centavos'],
        'PLN' => ['main' => 'Zloty', 'sub' => 'Grosz'],
        'QAR' => ['main' => 'Riyals', 'sub' => 'Dirhams'],
        'RON' => ['main' => 'Lei', 'sub' => 'Bani'],
        'RUB' => ['main' => 'Rubles', 'sub' => 'Kopecks'],
        'RWF' => ['main' => 'Francs', 'sub' => 'Centimes'],
        'SHP' => ['main' => 'Pounds', 'sub' => 'Pence'],
        'SVC' => ['main' => 'Colones', 'sub' => 'Centavos'],
        'STD' => ['main' => 'Dobra', 'sub' => 'Cêntimos'],
        'SAR' => ['main' => 'Riyals', 'sub' => 'Halala'],
        'SCR' => ['main' => 'Rupees', 'sub' => 'Cents'],
        'SLL' => ['main' => 'Leones', 'sub' => 'Cents'],
        'SGD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'SYP' => ['main' => 'Pounds', 'sub' => 'Piastres'],
        'SZL' => ['main' => 'Lilangeni', 'sub' => 'Cents'],
        'SEK' => ['main' => 'Krona', 'sub' => 'Öre'],
        'TJS' => ['main' => 'Somoni', 'sub' => 'Diram'],
        'TZS' => ['main' => 'Shillings', 'sub' => 'Cents'],
        'THB' => ['main' => 'Baht', 'sub' => 'Satang'],
        'TOP' => ['main' => 'Paʻanga', 'sub' => 'Seniti'],
        'TTD' => ['main' => 'Dollars', 'sub' => 'Cents'],
        'TND' => ['main' => 'Dinars', 'sub' => 'Millimes'],
        'TRY' => ['main' => 'Lira', 'sub' => 'Kuruş'],
        'TMT' => ['main' => 'Manat', 'sub' => 'Tenge'],
        'UGX' => ['main' => 'Shillings', 'sub' => 'Cents'],
        'UAH' => ['main' => 'Hryvnia', 'sub' => 'Kopiyky'],
        'AED' => ['main' => 'Dirhams', 'sub' => 'Fils'],
        'UYU' => ['main' => 'Pesos', 'sub' => 'Centésimos'],
        'UZS' => ['main' => 'Soums', 'sub' => 'Tiyin'],
        'VUV' => ['main' => 'Vatu', 'sub' => 'Centimes'],
        'VEF' => ['main' => 'Bolívares', 'sub' => 'Céntimos'],
        'VND' => ['main' => 'Dong', 'sub' => 'Xu'],
        'YER' => ['main' => 'Rials', 'sub' => 'Fils'],
        'ZMW' => ['main' => 'Kwacha', 'sub' => 'Ngwee'],
        'ZWL' => ['main' => 'Dollars', 'sub' => 'Cents'],
    ],

    // Pattern-based mappings for currency families
    'patterns' => [
        'dollar' => [
            'codes' => ['USD', 'CAD', 'AUD', 'NZD', 'SGD', 'HKD', 'TWD', 'FJD', 'BMD', 'BBD', 'BZD', 'KYD', 'GYD', 'SRD', 'XCD', 'LRD', 'NAD'],
            'words' => ['main' => 'Dollars', 'sub' => 'Cents']
        ],
        'euro' => [
            'codes' => ['EUR'],
            'words' => ['main' => 'Euros', 'sub' => 'Cents']
        ],
        'pound' => [
            'codes' => ['GBP', 'EGP', 'SYP', 'LBP', 'SDG', 'SSP', 'FKP', 'GIP', 'SHP'],
            'words' => ['main' => 'Pounds', 'sub' => 'Pence']
        ],
        'yen' => [
            'codes' => ['JPY'],
            'words' => ['main' => 'Yen', 'sub' => 'Sen']
        ],
        'franc' => [
            'codes' => ['XAF', 'XOF', 'XPF', 'CHF', 'BIF', 'RWF', 'DJF', 'GNF', 'KMF', 'CDF', 'SCR', 'MUR', 'HTG'],
            'words' => ['main' => 'Francs', 'sub' => 'Centimes']
        ],
        'rupee' => [
            'codes' => ['INR', 'LKR', 'MUR', 'SCR', 'NPR', 'PKR'],
            'words' => ['main' => 'Rupees', 'sub' => 'Cents']
        ],
        'peso' => [
            'codes' => ['MXN', 'ARS', 'CLP', 'COP', 'UYU', 'PHP', 'DOP', 'CUP', 'CUC', 'BOB', 'VES', 'CRC', 'GTQ', 'HNL', 'NIO', 'PAB', 'SVC'],
            'words' => ['main' => 'Pesos', 'sub' => 'Centavos']
        ],
        'dinar' => [
            'codes' => ['KWD', 'BHD', 'IQD', 'JOD', 'LYD', 'TND', 'DZD'],
            'words' => ['main' => 'Dinars', 'sub' => 'Fils']
        ],
        'shilling' => [
            'codes' => ['KES', 'UGX', 'TZS', 'SOS'],
            'words' => ['main' => 'Shillings', 'sub' => 'Cents']
        ],
        'krone' => [
            'codes' => ['NOK', 'DKK'],
            'words' => ['main' => 'Krone', 'sub' => 'Øre']
        ],
        'krona' => [
            'codes' => ['SEK', 'ISK'],
            'words' => ['main' => 'Krona', 'sub' => 'Öre']
        ],
        'rial' => [
            'codes' => ['OMR', 'YER', 'IRR'],
            'words' => ['main' => 'Rials', 'sub' => 'Fils']
        ],
        'dirham' => [
            'codes' => ['AED', 'MAD'],
            'words' => ['main' => 'Dirhams', 'sub' => 'Fils']
        ],
        'lira' => [
            'codes' => ['TRY'],
            'words' => ['main' => 'Lira', 'sub' => 'Kuruş']
        ],
        'ruble' => [
            'codes' => ['RUB', 'BYR'],
            'words' => ['main' => 'Rubles', 'sub' => 'Kopecks']
        ],
    ],

    // Default fallback for unknown currencies
    'fallback' => ['main' => 'Units', 'sub' => 'Subunits']
];
